# Generated by Django 3.0.5 on 2020-04-25 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moods', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mood',
            name='category',
        ),
        migrations.AddField(
            model_name='mood',
            name='title',
            field=models.CharField(default='Title', max_length=50),
            preserve_default=False,
        ),
    ]
